### ISSUE TITLE
[Bug] Any children on an animated element gets mounted twice and the second ref is unusable

### ISSUE THREAD

**Issue by vanillacode314** [Aslemammad/solid-spring#1]
## Repro
https://codesandbox.io/s/solidspringdoublemountrepro-7jqzuv?file=%2Fsrc%2Fmain.tsx

## Workaround
```js
function() {
  let myRef
  return (
    <animated.div style={{'backgroud-color':'red',...expand()}}>
      <div ref={(el)=> {
          if (myRef) return
          myRef = el
        }}
      >
        I get mounted twice and the second ref is unusable
      </div>
    </animated.div>
  )
}
```

**Comment by Aslemammad** [comment]
Interesting, Anyone interested for this?

**Comment by vanillacode314** [comment]
what do you mean by interested?

**Comment by Aslemammad** [comment]
I mean interested in working/solving on this issue.

**Comment by vanillacode314** [comment]
I might if you can give me some direction as where should I look in  the codebase

**Comment by Aslemammad** [comment]
The best thing to do is to put `debugger` in your code or the solid-spring source code! That's the best way to debug honestly!
